site_name: Scrape Up
site_description: A web-scraping-based python package that enables you to scrape data from various platforms like GitHub, Twitter, Instagram, or any useful website.
site_url: https://github.com/Clueless-Community/scrape-up

nav:
- Scrape Up: index.md
- Contributing: CONTRIBUTING.md
- Installation: installation.md
- Usage: 
  - 'Usage': uses/usage.md
  - 'GitHub': uses/github.md
  - 'Gitlab': uses/gitlab.md
  - 'Instagram': uses/instagram.md
  - 'Internshala': uses/internshala.md
  - 'Kooapp': uses/kooapp.md
  - 'Medium': uses/medium.md
  - 'Hackernews': uses/Hackernews.md
  - 'Twitter': uses/Twitter.md
  - 'Leet Code': uses/leetcode.md
  - 'Finance': uses/Finance.md
  - 'Flex Jobs': uses/flexjobs.md
  - 'IMDb': uses/imdb.md
  - 'Coursera': uses/coursera.md
  - 'Wikipedia': uses/wikipedia.md
  - 'Amazon': uses/uses/amazon.md
  - 'Flipkart': uses/flipkart.md
  - 'Spotify': uses/spotify.md
  - 'Ask-Ubuntu': uses/ask-ubuntu.md
  - 'Eazydiner': uses/eazydiner.md
  - 'Stack Overflow': uses/stackoverflow.md
  - 'Tech Crunch': uses/techcrunch.md
  - 'Youtube': uses/youtube.md
  - 'Google News': uses/googlenews.md
  - 'Hashnode': uses/hashnode.md
  - 'Reddit': uses/reddit.md
  - 'Devpost': uses/devpost.md
  - 'Luma': uses/luma.md
- Code of Conduct: CODE_OF_CONDUCT.md

theme:
  features:
  - header.autohide
  name: material
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
repo_name: /scrape-up
repo_url: https://github.com/Clueless-Community/scrape-up